// examples/nextjs-app/pages/auth.tsx
import React from "react";
import TorusSdk, { RedirectResult } from "@toruslabs/torus-direct-web-sdk";
import dynamic from "next/dynamic";

const ReactJsonView = dynamic(() => import("react-json-view"));

interface IState {
  loginDetails?: RedirectResult | null;
}

interface IProps {}

class RedirectAuth extends React.Component<IProps, IState> {
  constructor(props: IProps) {
    super(props);
    this.state = {
      loginDetails: null,
    };
  }

  async componentDidMount() {
    const torusdirectsdk = new TorusSdk({
      baseUrl: window.location.origin,
      redirectPathName: "auth",
      enableLogging: true,
      uxMode: "redirect",
      network: "testnet",
    });
    const loginDetails = await torusdirectsdk.getRedirectResult();
    this.setState({
      loginDetails,
    });
  }

  render() {
    const { loginDetails } = this.state;
    return (
      <div className="App">
        <div className="about">
          <h1>This is the redirected page</h1>
          {loginDetails && <ReactJsonView src={loginDetails} />}
        </div>
      </div>
    );
  }
}

export default RedirectAuth;

// examples/vue-app-redirect-flow/src/views/Auth.vue
<template>
  <div class="about">
    <h1>This is the redirected page</h1>
    <code>
      {{ loginDetails }}
    </code>
  </div>
</template>

<script>
import TorusSdk from "@toruslabs/torus-direct-web-sdk";

export default {
  data() {
    return {
      loginDetails: ""
    };
  },
  async mounted() {
    const torusdirectsdk = new TorusSdk({
      baseUrl: location.origin,
      redirectPathName: "auth",
      enableLogging: true,
      uxMode: "redirect",
      network: "testnet"
    });
    const loginDetails = await torusdirectsdk.getRedirectResult();
    console.log(loginDetails);
    this.loginDetails = JSON.stringify(loginDetails, null, 2);
  }
};
</script>
